name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TiagoOliverDev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: snake-bot
          author_email: snake@bot.com
          message: "generated snake"
          add: "dist/github-contribution-grid-snake.svg"
